<<<<<<< HEAD
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels: 
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 80
=======
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels: 
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 80
>>>>>>> 第一次添加
          protocol: TCP