apiVersion: apps/v1
kind: Deployment
metadata:
  name: naing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: naing-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.7.6
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
