<<<<<<< HEAD
=======
<<<<<<< HEAD
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: test
          servicePort: 18080
      - path: /bar
        backend:
          serviceName: test2
          servicePort: 18080
=======
>>>>>>> ORIG_HEAD
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: test
          servicePort: 18080
      - path: /bar
        backend:
          serviceName: test2
          servicePort: 18080
<<<<<<< HEAD
=======
>>>>>>> 第一次添加
>>>>>>> ORIG_HEAD
