<<<<<<< HEAD
apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    name: liveness-exec
spec:
  containers:
  - name: liveness
    image: radial/busyboxplus
    imagePullPolicy: IfNotPresent
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy;sleep 20;rm -rf /tmp/healthy;sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5 #初始化5秒后开始探测
      periodSeconds: 5 #5秒探测一次
=======
apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    name: liveness-exec
spec:
  containers:
  - name: liveness
    image: radial/busyboxplus
    imagePullPolicy: IfNotPresent
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy;sleep 20;rm -rf /tmp/healthy;sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5 #初始化5秒后开始探测
      periodSeconds: 5 #5秒探测一次
>>>>>>> 第一次添加
    