<<<<<<< HEAD
=======
<<<<<<< HEAD
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
=======
>>>>>>> ORIG_HEAD
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
<<<<<<< HEAD
=======
>>>>>>> 第一次添加
>>>>>>> ORIG_HEAD
      storage: 3Gi