<<<<<<< HEAD
=======
<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  selector: #要和pod的labels的一致
    app: nginx-pod
  ports:
  - protocol: TCP
    port: 80 #service的ip地址
    targetPort: 80 #容器IP地址
=======
>>>>>>> ORIG_HEAD
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  selector: #要和pod的labels的一致
    app: nginx-pod
  ports:
  - protocol: TCP
    port: 80 #service的ip地址
    targetPort: 80 #容器IP地址
<<<<<<< HEAD
=======
>>>>>>> 第一次添加
>>>>>>> ORIG_HEAD
