<<<<<<< HEAD
apiVersion: v1
kind: Pod
metadata:
  name: test-configmap-env-pod
spec:
  containers:
    - name: test-container
      image: radial/busyboxplus
      imagePullPolicy: IfNotPresent
      command: ['/bin/sh','-c','sleep 100000']
      envFrom:
      - configMapRef:
=======
apiVersion: v1
kind: Pod
metadata:
  name: test-configmap-env-pod
spec:
  containers:
    - name: test-container
      image: radial/busyboxplus
      imagePullPolicy: IfNotPresent
      command: ['/bin/sh','-c','sleep 100000']
      envFrom:
      - configMapRef:
>>>>>>> 第一次添加
          name: test-config