apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: nginx-emptydir
  name: nginx-emptydir
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-emptydir
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-emptydir
    spec:
      containers:
      - image: nginx:1.9.2
        imagePullPolicy: IfNotPresent
        name: nginx-emptydir
        volumeMounts:
          - mountPath: /opt
            name: emptydir-volume
      - image: nginx:1.9.2
        imagePullPolicy: IfNotPresent
        name: nginx-emptydir2
        command:
          - sh
          - -c 
          - sleep 36000
        volumeMounts:
          - mountPath: /mnt
            name: emptydir-volume
      volumes:
        - name: emptydir-volume
          emptyDir: {}
     
