apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx-pod
  ports:
  - name: http
    protocol: TCP
    port: 18080
    targetPort: 80
  externalIPs:
    - 192.168.234.130 
