apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  containers:
  - name: frontend
    image: kubeguide/guestbook-php-frontend
    imagePullPolicy: IfNotPresent
    env:
    - name: GET_HOSTS_FROM 
      value: env
    ports:
    - containerPort: 80
  - name: redis 
    image: kubeguide/redis-master
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
