apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-harbor
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets: #镜像库的secret
      - name: my-harbor
      containers:
      - name: nginx
        image: 192.168.26.201/test/nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 100Mi
#kubectl create secret docker-registry my-harbor --docker-server=192.168.26.201 --docker-username=test --docker-password=Cctv1234! --docker-email=test@qq.com