<<<<<<< HEAD
=======
<<<<<<< HEAD
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:                                      # 使用node亲和进行判断
      requiredDuringSchedulingIgnoredDuringExecution:  # 硬策略
            nodeSelectorTerms:                         # 节点选择器的条件
            - matchExpressions:                        # 定义匹配的表达式
              - key: app                               # label 的key
                operator: In                           # 定义判断的方式有多种 ，In NotIn,Exists,DoesNotexist,Gt,Lt.
                values:                                # labe 的values
                - nginx1
    containers:
    - name: with-node-affinity
=======
>>>>>>> ORIG_HEAD
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:                                      # 使用node亲和进行判断
      requiredDuringSchedulingIgnoredDuringExecution:  # 硬策略
            nodeSelectorTerms:                         # 节点选择器的条件
            - matchExpressions:                        # 定义匹配的表达式
              - key: app                               # label 的key
                operator: In                           # 定义判断的方式有多种 ，In NotIn,Exists,DoesNotexist,Gt,Lt.
                values:                                # labe 的values
                - nginx1
    containers:
    - name: with-node-affinity
<<<<<<< HEAD
=======
>>>>>>> 第一次添加
>>>>>>> ORIG_HEAD
      image: registry.aliyuncs.com/google_containers/pause:3.2