<<<<<<< HEAD
=======
<<<<<<< HEAD
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-env
type: Opaque #加密
data:
  username: YWRtaW4=
=======
>>>>>>> ORIG_HEAD
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-env
type: Opaque #加密
data:
  username: YWRtaW4=
<<<<<<< HEAD
=======
>>>>>>> 第一次添加
>>>>>>> ORIG_HEAD
  password: cmVkaGF0