apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    envFrom:
      - secretRef:
          name: mysecret-env  # 要和刚才创建的名字一样

